#!/bin/bash

if [[ $(echo `ps -ef | grep xflux | grep -v grep` | wc -c) -ne 1 ]]; then
  echo 'One instance of helux is already running.'
  echo 'Running multiple instances simultaneously will cause artifacts.'
  echo 'You can stop previous instance by running: helux-off'
else
  #get directory path to here
  SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  helux="/bin/helux-on"
  heluxOn="$DIR$helux"
  node $heluxOn $1
fi
