#!/bin/bash
#npm install
npm install
#get directory path to here
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
SOURCE="$(readlink "$SOURCE")"
[[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
#path to on and off scripts
hlxon="/helux-on"
hlxoff="/helux-off"
#path to bash scripts
pathToHlxOn="$DIR$hlxon"
pathToHlxOff="$DIR$hlxoff"
#create symlincs
ln -s $pathToHlxOn /usr/bin/helux-on
ln -s $pathToHlxOff /usr/bin/helux-off
#installed
printf 'Helux has been installed successfully\n'
printf '*** *** ***\n\n'
printf 'To start Helux run:   helux-on {YOUR LOCATION}\n'
printf 'To stop:              helux-off\n'
printf '\n*** *** ***\n'
printf 'to uninstall run: sudo ./uninstall-helux\n'
